version: '3'

services:
  fwportal_ics:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: 'icodr8/fwportal_ics:latest'
    environment:
      - FWPORTAL_USER=${FWPORTAL_USER}
      - FWPORTAL_PASSWORD=${FWPORTAL_PASSWORD}
      - FWPORTAL_DEVICE_ID=${FWPORTAL_DEVICE_ID}
      - FWPORTAL_DIENSTSTELLEN=${FWPORTAL_DIENSTSTELLEN}
      - FWPORTAL_FWMOBILE_VERSION=${FWPORTAL_FWMOBILE_VERSION}
      - DEBUG=${DEBUG}

    volumes:
      - fwportal-ics-data:/fwportal-ics/data:rw

volumes:
  fwportal-ics-data: {}
